apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-jan142026-1-app
  namespace: openshift-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/chatbot-jan142026-1/overlays/development
    repoURL: https://github.com/redhat-appstudio-mjf/chatbot-jan142026-1-gitops.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: chatbot-jan142026-1
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
