apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: chatbot-jan142026-1
  janus-idp.io/tekton: chatbot-jan142026-1
  backstage.io/kubernetes-id: chatbot-jan142026-1
  backstage.io/kubernetes-namespace: chatbot-jan142026-1
  app.kubernetes.io/part-of: chatbot-jan142026-1
resources:
  - initialize-namespace/
  - deployment-model-server.yaml
  - service-model-server.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
